### ISSUE TITLE
Burada providerdan dizi geldiğinden ve dizinin ilk elemanının dolar kuru olduğundan nasıl emin olabilirsin?

### ISSUE THREAD

**Issue by bekco** [kaanosman/currencyComparator#1]
Provider Currency Result dönerek daha iyi bir çözüm yapabilir misin burada?

https://github.com/kaanosman/currencyComparator/blob/9e4f0fbc669cc7ec110c42211d198405151e5192/src/CurrencyBundle/Command/CurrencyRateCommand.php#L43

**Comment by kaanosman** [comment]
Dizi oluşturuldu.
