### ISSUE TITLE
Bu commandın görevi karşılaştırma olmamalı, yeni bir provider eklendiğinde bu kod seni uğraştıracak, servislere bırakmalısın bu tip işleri.

### ISSUE THREAD

**Issue by bekco** [kaanosman/currencyComparator#2]
https://github.com/kaanosman/currencyComparator/blob/9e4f0fbc669cc7ec110c42211d198405151e5192/src/CurrencyBundle/Command/CurrencyRateCommand.php#L32

**Comment by kaanosman** [comment]
Kurları karşılaştıran servis yazıldı.
